### ISSUE TITLE
I think `LFP` should be a `TimeSeries`

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-schema#114]
Would it be possible to change it? Are there any objections?

**Comment by oruebel** [comment]
See also #112

**Comment by ajtritt** [comment]
Can you provide some justification? LFP contains an ElectricalSeries (which is a TimeSeries).

**Comment by bendichter** [comment]
I'd like to put it in acquisition instead of a processing module. I think that requires that it's a TimeSeries?

**Comment by oruebel** [comment]
I don't think acquistion is the right place for this. acquistion is intended for "data streams recorded from the system..." not for processed data. See here for details on acquistion: http://nwb-schema.readthedocs.io/en/latest/format.html#groups-acquisition

**Comment by neuromusic** [comment]
While we're are it I'd like to nominate a DfOverF and Fluorescence, both of which simply point to an RoiResponseSeries. FilteredEphys should be on the list, too.

Can I flip the Q around @ajtritt and ask why the schema relies so much on these objects that simply point to other objects that actually contain the data the first object describes? We end up having to define a time series, put the data in it, then define the container to simply wrap it (and add yet another "name" and "source" while we're at it #53) 

Isn't the reliance on "containers" like this a relic of the 1.0.6 module/interface structure?

**Comment by neuromusic** [comment]
more specifically, the justification is that the ElectricalTimeSeries is the LFP, not the wrapper called "LFP"

**Comment by bendichter** [comment]
A common data structure for multiunit recordings is to store for a given channel (or channel group):

* detected spike event times
* detected spike event waveforms at a high sampling rate in windows around those times
* low sampling rate voltage time series data (often called LFP)

These are all forms of raw data because they are often the first data stored to the disk permanently. Am I correct in thinking that in this case LFP would earn a place in `acquisition`?

**Comment by neuromusic** [comment]
> I'd like to put it in acquisition instead of a processing module. I think that requires that it's a TimeSeries?

Yeah @bendichter this is one of the places where NWB enforces provenance through the schema. Anything that isn't raw belongs in processing & therefore requires you build modules, etc.

**Comment by neuromusic** [comment]
@bendichter the assumption in NWB is that LFP is not "raw" but has been extracted from the full bandwisth, high-sampling rate acquisition through some digital processing 🤷‍♂️

**Comment by bendichter** [comment]
yeah, I understand that and I think it's reasonable provided the high frequency signal is stored to disk as well, but I want to make the point that sometimes LFP is the only full voltage series stored, and in those cases it should be considered raw.

**Comment by neuromusic** [comment]
I'd prefer to burn down the whole acquisition/processing distinction. There are better ways to track provenance.

**Comment by neuromusic** [comment]
but yes, I think your point highlights that forcing particular kinds of data into acquisition or processing based on assumptions about the data provenance is not a good design.

**Comment by bendichter** [comment]
I agree that the current setup is a bit problematic. I'm running into issues also with storing simulated data. There the raw data is the spike times because that's all that's saved, but I have to put them in a processing module, which doesn't feel like the most intuitive choice. I think letting the user mark specific data objects as raw makes sense, but I'd like a more flexible way to do it.

**Comment by oruebel** [comment]
@neuromusic these specification come from 1.0.6. I don't know the exact reasons why some of what used to be ``Interfaces`` in 1.0.x do this but my best guess is:

* Before we relaxed some of the requirements in the format and introduced ``NWBContainer`` as a base type, all objects in ``/acquistion`` where ``TimeSeries`` and all objects in ``/processing`` had to be ``Interfaces ``. As a result of this (unless you would allow multiple inheritance), the only way to get a TimeSeries into processing was to wrap it and conversely it was not possible to place an ``Interface`` into ``/processing`` The schema in that sense strictly separated between acquistion and processing. 

Let me summarize what I think the different pieces of the discussion are.

1) Should some of the neurodata_types that are used for processed data (e.g., Clustering, LFP, etc.) be TimeSeries. 
   * Generally speaking, I think the answer here is yes, but needs to be decided on a case-by-case basis. I.e., we should go through all the types that used to be ``Interfaces`` in NWB 1.0.6 and see if they should be TimeSeries instead. @ajtritt  and I had this discussion early on in the project and it was also I think on the original agenda for the hackathon last year but simply had not made it far enough up the priority list yet. 
2) The second question is whether the schema should continue to strictly enforce the separation between ``acquisition`` and ``processing``. 
   * I'm not sure what the right answer to this question is right now without deeper review and discussion of this topic. However, I think we can separate the discussion of 2) from 1), because if we decide we should enforce the distinction between processing and acquistion in the schema then this can be fixed by creating a type ``RawTimeSeries`` (that would basically do nothing else but inherit from TimeSeries) and then have ``acquistion`` only allow ``RawTimeSeries``. 

As such, I would propose the following:

* Merge this issue and #112
* Create a list of neurodata_types that used to be ``Interfaces`` that are basically just wrapping ``TimeSeries``
* Review the list and decide on a case-by-case basis which ones should be changed and how
* Identify a POC for implementing the changes in the schema and PyNWB (i.e., I don't think @ajtritt should do this one)

For reference, here the list of all types that used to be ``Interface`` in 1.0.6:

- BehavioralEpochs  
- BehavioralEvents
- BehavioralTimeSeries
- ClusterWaveforms
- Clustering  
- CompassDirection
- DfOverF 
- EventDetection
- EventWaveform
- EyeTracking
- FeatureExtraction 
- FilteredEphys
- Fluorescence
- ImageSegmentation
- ImagingRetinotopy
- LFP 
- MotionCorrection
- Postion
- PupilTracking
- UnitTimes

**Comment by bendichter** [comment]
Thanks for the thoughtful response, Oliver. 

1) 
Besides the issue of raw/acquisition vs. processing, TimeSeries is important because it allows you to link with epochs. As such, I think anything where it makes sense to link epochs should inherit from TimeSeries:
* BehavioralEvents
* BehavioralTimeSeries
* Clustering
* CompassDirection
* DfOverF
* EventDetection
* EyeTracking
* FilteredEphys
* Fluorescence
* LFP
* Postion
* PupilTracking
* UnitTimes

2) While we are discussion it, I'd like to be able to put non-time series objects in acquisition as well, for instance parallel-optimized spike times, 3D cortical mesh, etc.

**Comment by oruebel** [comment]
I've create a public google doc so that we can identify which specific changes we should make. Hopefully this will a) make it easier for us to keep track of what the actual proposed changes are b) save some time writing issues, c) allows us to have a good record for the release notes. Please have a look at the doc and add your comments:

https://docs.google.com/document/d/1g3fjXU8CIMSnFaudAUs9MHN_4PVSlO5IaGZQaHD_GrU/edit?usp=sharing

In the document, please also have a look at the potential side effects (and add any effects that I've forgotten). When arguing for/against a particular change, please indicate why the create side-effects are reasonable. 

Just to be clear, I think many of these changes make sense. But this is a somewhat fundamental change and so I want to make sure that we are not inadvertently creating some major issues.

**Comment by oruebel** [comment]
@bendichter do you think implementing this could be a project for you at the Allen hackathon?

**Comment by bendichter** [comment]
@oruebel sure

**Comment by ehennestad** [comment]
This is an interesting discussion, and my initial impression is that having Interfaces that wraps time series adds a layer of complexity that does not serve a purpose, even though it might have historically. 

As far as I can see from the schemas, most of these wrappers still exist. What was the reason to not move forward on this issue?

**Comment by bendichter** [comment]
@ehennestad the truth is other more mission-critical issues took priority. At this point, this ideal will probably have to be pushed back to 3.0, as it would cause an avalanche of backwards incompatibility.
