### ISSUE TITLE
Restructure /general/subject to make easier to extend

### ISSUE THREAD

**Issue by ajtritt** [NeurodataWithoutBorders/nwb-schema#120]
# Problem
/general/subject currently stores data that apply to the NWBFile type. Users need to extend the NWBFile type to add additional subject metadata. 

# Proposal
Replace the specification for /general/subject with the neurodata_type Subject. This new type will contain the following fields:

1. age
2. description
3. genotype
4. sex
5. species
6. subject_id
7. weight

This amounts to assigning a neurodata_type to the /general/subject group specification.

**Comment by neuromusic** [comment]
this is an optional type with all optional fields, right?

**Comment by bendichter** [comment]
Over 89 years old, the age of a human subject is considered protected personal identifying information. We might want to somehow allow for an "over 89" option for age.

https://www.hhs.gov/hipaa/for-professionals/privacy/special-topics/de-identification/index.html

**Comment by bendichter** [comment]
also, we'll need the ability to specify more than one subject. Here in the Soltesz lab it's quite common to record two or more mice simultaneously into the same file.

edit: the above is not true-- I was mistaken. See below

**Comment by oruebel** [comment]
> this is an optional type with all optional fields, right?

@neuromusic correct. The main reason for this change is to make it possible to more easily extend ``/general/subject`` without having to extend ``NWBFile`` itself.

**Comment by oruebel** [comment]
> We might want to somehow allow for an "over 89" option for age.

@bendichter age is just a text field right now, so writing somtehing like ">89" is possible right now

**Comment by ajtritt** [comment]
@bendichter we can make set the current group name to be a default, so users can add multiple subjects with different names. Does that work?

**Comment by oruebel** [comment]
> we'll need the ability to specify more than one subject

Allowing this from a schema perspective would be simple (just change the name of subject to default_name and change the quantity flag to "zero_or_more"). However, I think this has broader implications. Specifically, once we add multiple subjects, how do you know which TimeSeries or NWBContainer belongs to which subject?

**Comment by bendichter** [comment]
@oruebel and @ajtritt yeah those solutions seem like they would work, thanks!

**Comment by bendichter** [comment]
@oruebel re: multiple subjects

That's a good question. I'd imagine that your raw ElectricalSeries objects would actually have columns from multiple subjects and it would be on the experimenter to label this. ElectricalSeries channels are associated with electrode groups -> devices. Maybe we could specify a subjects for devices? This would only be necessary if there is more than one subject in the file.

The other solution would be to enforce only one subject per file, but then we have a pretty big departure from the actual data acquisition.

**Comment by oruebel** [comment]
@bendichter this issue seems to affect essentially all types for processed and raw data, not just ElectricalSeries, i.e., I think we would need a more general solution for this. What is the motivation for storing data from multiple subjects in one file?

**Comment by bendichter** [comment]
@oruebel 
The motivation is that's how data is acquired in some labs. Channel come from the two 2 or more animals into a single DSP and are stored in the same file. So we would either have to 

a) set up the software to write to 2 different NWB files simultaneously or
b) concede that NWB won't be the best format for acquiring this data and make a conversion step where a single acquisition file of some other format is converted into multiple NWB files.

I'd be fine with (b), it just seemed from the structure of NWB that a goal might have been eventually to have data go straight to NWB without any intermediate formats.

**Comment by oruebel** [comment]
> have data go straight to NWB without any intermediate formats

Yes, I agree.

> we'll need the ability to specify more than one subject

I'm not against to allow this. I'm just trying to figure out how we can ensure that we maintain a clear association between data and metadata (e.g., subject, device etc.). Honestly, I think this is a bit of a deeper problem in the current schema where ``/general`` is a container for more-or-less global metadata but there is not always an explicit association of metadata with data. For device, e.g., several of the types have softlinks to the device. Ultimately, I guess this goes back to the question how we want to deal with provenance in NWB:N. 

>  2 or more animals into a single DSP and are stored in the same file

Just for my own understanding, when streaming data from multiple subjects to a single DSP and file, I assume this means that you are creating a single 2D array of ``electrodes x time`` where each electrode may belong to a different subject or device.

@ajtritt @bendichter Let me propose the following solution for now:

1)  Change ``Subject`` to have ``default_name=subject`` and ``quantity=zero_or_more``
2) Add a group ``/general/subjects`` that can store multiple ``Subject`` containers. This is mainly for consistency in the schema, since devices etc. are also collected in dedicated groups in ``/general``
3) Create a new ticket to discuss solutions for how to associate subjects, devices etc. with specific datasets to make sure we can answer the question of: a) which subject does a dataset belong to and b) which data belongs to a subject.

**Comment by bendichter** [comment]
ok actually I just went and clarified with the experimentalists and they say they write to multiple files simultaneously and don't have multiple animals per file.

**Comment by bendichter** [comment]
Sorry for passing on misinformation. This could still be an issue that comes up later I suppose, but it's not an issue for any of the labs I am dealing with right now that I know of. 

@oruebel @ajtritt

**Comment by oruebel** [comment]
@bendichter thanks for the clarification.

**Comment by neuromusic** [comment]
"concede that NWB won't be the best format for acquiring this data and make a conversion step where a single acquisition file of some other format is converted into multiple NWB files."

this is how we do it.

I'm highly skeptical that one file format can be simultaneously optimized for (a) acquisition, (b) offline processing, (c) provenance tracking, and (d) exchange.

**Comment by ajtritt** [comment]
For the record, Ophys, Extracellular Ephys, Intracellular Ephys, and Optogenetic TimeSeries types all point back to some metadata container that points to a device. If device points to a subject, then we cover almost all of the types.
