### ISSUE TITLE
request: `StaticImage`

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-schema#129]
The Allen Institute is interested in storing a single frame that is the maximum image across time per channel (https://gist.github.com/neuromusic/b44fa185f03b7e588af7f5e7ccb52bdd). Similarly, the Losonczy Lab routinely stores mean frames across time per channel (http://www.losonczylab.org/sima/1.3.2/tutorial.html#id20). Currently, as far as I know, the best way to store this data is as an `ImageSeries` of length 1. This seems like a non-ideal structure for storing this data (what does `timestamps` mean in this context?) I propose the addition of a `StaticImage` data structure for storing these types of data that are not associated with specific times.

**Comment by ajtritt** [comment]
Good idea @bendichter. Please provide a specification that does this and we can go from there. (PyNWB source code is fine to start with)

**Comment by bendichter** [comment]
fyi @neuromusic

**Comment by jeffteeters** [comment]
fwiw, the format does allows storing single images in `/acquisition/images`.  Perhaps the schema for that could be leveraged.

**Comment by ajtritt** [comment]
@jeffteeters thanks for the reminder. I forgot.. way back when we were restructuring the schema, I added a neurodata_type "Image".  It's pretty barebones, but before anything gets added, I suggest looking at it: http://nwb-schema.readthedocs.io/en/latest/format.html#image

**Comment by bendichter** [comment]
great, thanks!

**Comment by campagnola** [comment]
An issue to consider: There is a lot of common metadata that might be shared between `Image` and `ImageSeries` (examples: bit depth, exposure time, binning, spatial transform, illumination, filtering, etc.). Rather than duplicating, it might make sense for each to have something like an `ImageMeta` subgroup that can be attached to any image data class.

This gets a little hairy because we have many `ImageSeries` subclasses like `TwoPhotonSeries` and `OpticalSeries` that would each imply different types of metadata. I think a natural solution is to have a set of `ImageMeta` subclasses that each describe different types of imaging parameters, and any `Image` or `ImageSeries` can attach 0-or-more of these metadata classes. Examples:

```
ImageMeta:
    bit_depth
    transform
MicroscopyImageMeta:
    objective_name
    objective_na
    objective_magnification
CameraImageMeta:
    exposure_time
    binning
    sensor_roi
    camera_model
TwoPhotonImageMeta
    pmt_gain
    scan_line_rate
    dwell_time
    laser_wavelength
    laser_power
FilteringImageMeta:
    emission_filter_wavelength
    emission_filter_name
IlluminationImageMeta:
    illumination_power
    excitation_filter_wavelength
    excitation_filter_name
```

**Comment by neuromusic** [comment]
+💯 

the other need for this is as a target of an IndexSeries... in which case, we are talking about a stack of static images

**Comment by campagnola** [comment]
Just to add to the noise, static images can be:
* 2D (y, x)
* 3D (z, y, x)
* 2D with channels (y, x, c)
* 3D with channels (z, y, x, c)
* Probably others

For large images, the data are probably acquired in a particular order where it can be expensive to re-order the axes during acquisition (so you might also want to support (c, y, x), (c, z, y, x), etc.). This suggests there should be some way to describe the order of axes. This also applies to ImageSeries.
