### ISSUE TITLE
Modify dataset spec language to allow compound data types to support table specification

### ISSUE THREAD

**Issue by ajtritt** [NeurodataWithoutBorders/nwb-schema#13]
Originally reported by: **Andrew Tritt (Bitbucket: [ajtritt](https://bitbucket.org/ajtritt), GitHub: [ajtritt](https://github.com/ajtritt))**

----------------------------------------

**Goal**: enhance dataset specification language to allow specification of table datasets

**Proposed solution**: Allow dtype key of the dataset specification language to take the following options:

* scalars: maintains current functionality
* list of dicts: Use this to specify column spec
    * each dict takes two keys: 
        * *column*: specifies column name
        * *dtype*: specifies the data type of the column

**HDF5 Storage**: In HDF5 such a data type would be represented as a compound data type/

----------------------------------------
- Bitbucket: https://bitbucket.org/lblneuro/nwb-schema/issue/13

**Comment by oruebel** [comment]
In terms of the specification language this seems fine. I would recommend the following changes to the proposal:

- Instead of _column_ I think it would be better to use the key _label_ or _name_ .  The reason is this spec creates a compound data type, which is more general than just a table. While we will initially use this primarily to represent tables via 1D arrays with a compound data type, the dimensionality of the array is not restricted, i.e., we could equally well use this to define an n-dimensional array with a compound data type.  
- Should we also add a key 'doc' to allow users to further describe each component of a compound type in the specification language?

**Comment by ajtritt** [comment]
@oruebel I agree with allowing a *doc* key for each *label*

**Comment by t-b** [comment]
Regarding HDF5 storage: Is it planned to allow compound of compound datasets? Not all HDF5 progamming APIs allow accessing these.

**Comment by oruebel** [comment]
I believe the proposed changes to the spec will only allow for "flat" compound types at this point.

**Comment by t-b** [comment]
@oruebel Thanks.

**Comment by oruebel** [comment]
@ajtritt can this issue be closed?
