### ISSUE TITLE
storing trial data

### ISSUE THREAD

**Issue by ajtritt** [NeurodataWithoutBorders/nwb-schema#152]
1) define trial data types
    - AbstractTrialData neurodata_type?
    - categorical?
        - what types of categories?
    - response and stimulus?
2) add location for trials in NWBFile

Maybe define state-machine type?

**Comment by bendichter** [comment]
The categorial description of trials will generally correspond to a controlled differentiation in stimulation, stimulus, behavior, etc. These categorical differences are often the key to the novelty of the experiment, so trying to anticipate and define a set of categorical variables that will work broadly is IMO going to be impossible. I would prefer a framework where one can easily define new features and attach sufficient meta-data to understand what they mean.

Also, we should not necessarily limit ourselves to categorical variables. Sometimes stimuli are from a continuous distribution, e.g. the [Newsome dot experiment](https://www.youtube.com/watch?v=xUcwbjaGGNM), and sometimes they are better represented by integers.

Here's an idea of how we might accomplish this:

* Each `TrialTable` should have the ability to hold zero or more `trial_feature`s which are additional columns in the table
* Each `trial_feature` should have `name`, `description`, `dtype` (any more?)
* There must be a data element per `trial_feature` per trial, with the option of having this element be a scalar or a vector per trial
* `dtype` should allow for any of the existing data types and an enumerated type. The enumerated type would be used for categorical data, and the allowable categories should be defined by the user. (the real feature here is categorical data. Enumerated types are not a necessity and there are other ways to do this that would work fine.)

I wouldn't be opposed to labeling response or stimulus in the `trial_feature` meta-data but I don't think that's an essential feature, because that should be obvious from the description.

**Comment by bendichter** [comment]
Similar to [BIDS](http://bids.neuroimaging.io/bids_spec1.1.0.pdf) section 8.5

**Comment by ajtritt** [comment]
> so trying to anticipate and define a set of categorical variables that will work broadly is IMO going to be impossible.

I don't mean the specific variables--I agree, that's impossible. I mean the dtypes of these variables. I'm thinking of having an abstract base type, and then a handful of instantiable subtypes. Something like this:

_AbstractTrialFeature_
  - _IntTrialFeature_
    - _CategorialFeature_
      -  array of ints that index into an array of categorical values. Additionally, it would have an attribute that holds a reference to the array of categorical values.
  - _FloatTrialFeature_
  - _StrTrialFeature_

The first dimension of these datasets would always be trial, so possible dimensions would be (None,) for scalar data  or (None, None) for vector data. 

Then _TrialTable_ is a group that contains 1 or more _AbstractTrialFeatures_. Users don't need to extend _TrialTable_. They would only need to extend _AbstractTrialFeature_ if they wanted to add another dtype.

> I wouldn't be opposed to labeling response or stimulus in the trial_feature meta-data but I don't think that's an essential feature, because that should be obvious from the description.

This would be a requirement for programability, not for human interpretation

**Comment by bendichter** [comment]
ok all that looks good to me
