### ISSUE TITLE
When is an ObjectMapper necessary/recommended?

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-schema#169]
I can't tell by the documentation when it would be a good idea to use an ObjectMapper for an extension. It's mentioned [here](https://pynwb.readthedocs.io/en/latest/extensions.html#incorporating-extensions).

**Comment by oruebel** [comment]
From the documentation: ``If your NWBContainer extension requires custom mapping of the NWBContainer class for reading and writing, you will need to implement and register a custom ObjectMapper.``

Let me try to clarify what this means. There are essentially four components here, the:

* **Spec** which defines how things should be stored
* **Container** which defines the API for using the data. See https://pynwb.readthedocs.io/en/latest/overview_software_architecture.html#container
* **Builder** which is an intermediary representation for I/O (consists of Groups, Datasets, Attributes etc.). See  https://pynwb.readthedocs.io/en/latest/overview_software_architecture.html#builder
* **ObjectMapper** which defines how attributes from the Container are mapped to objects in the spec and vice versa. The ObjectMapper deals with the mapping of containers to builders and vice versa.  See https://pynwb.readthedocs.io/en/latest/overview_software_architecture.html#objectmapper

The ObjectMapper, hence, defines how objects in the spec map to attributes in the container API and vice versa  For extensions you need a ObjectMapper in cases where the default mapping from spec objects to container attributes is insufficient. E.g., in the case of TimeSeries the attribute ``unit`` on the dataset ``data`` (i.e., ``data.unit``) would normally be mapped to an attribute ``data_unit`` on the TimeSeries container. Using the ObjectMapper this mapping is changed so that ``data.unit`` is instead mapped to just ``unit`` on the container. See here  https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/src/pynwb/io/base.py

In addition to "just" customizing names you can also define, e.g., how constructor arguments for the container are generated from the spec. In this way, you can, e.g., compute derived data in the ObjectMapper in order to make the data easier or more efficient to use in memory.

**Comment by oruebel** [comment]
Another example where the ObjectMapper is useful is for backward compatibility. E.g., the legacy module uses the ObjectMapper quite heavily. E.g.

https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/src/pynwb/legacy/io/ophys.py

**Comment by bendichter** [comment]
Ok got it, thanks!

**Comment by oruebel** [comment]
What do you think we can do to make this more clear in the documentation?

**Comment by bendichter** [comment]
An example would help

On Jun 12, 2018 7:12 PM, "Oliver Ruebel" <notifications@github.com> wrote:

What do you think we can do to make this more clear in the documentation?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/NeurodataWithoutBorders/nwb-schema/issues/169#issuecomment-396665667>,
or mute the thread

**Comment by ajtritt** [comment]
@oruebel I think we could expose the TimeSeries ObjectMapper to the world to demonstrate the functionality. For example, I think showing how we (will) use the `constructor_arg` decorator to designate a method for setting `timestamps` using `starting_time`/`rate` could be intuitive.

**Comment by oruebel** [comment]
I've updated the PyNWB docs and create the following pull request https://github.com/NeurodataWithoutBorders/pynwb/pull/532

@ajtritt I agree that exposing the TimeSeries ObectMapper to the world would be a good way to do this. We could also add something about object mappers to the tutorial: http://pynwb.readthedocs.io/en/latest/tutorials/general/extensions.html#sphx-glr-tutorials-general-extensions-py
