### ISSUE TITLE
Storing signal from non-neural electrodes

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-schema#229]
What is the appropriate way to handle voltage recordings that are from non-neural sources e.g. thermistor system in the environment? I feel this should still be in `/acquisition`, since this is still acquired measurements. It's clearly also a `TimeSeries`. I'd like to use `ElectricalSeries` but that presents an issue. `ElectricalSeries` requires referencing an electrode from an electrode table, but this table has columns that do not make sense for electrodes in the environment- position (if we did indicate position, it would be in a different reference frame), location (presumably this is a brain location for neural electrodes) and perhaps other columns that have been added to the electrodes table.  You could use null-like values for all of these columns, but that still leaves you with the non-ideal situation that you are putting electrodes in the same table that really do not belong together. 

Would it be possible to add another electrodes table specifically for non-neural electrodes? We could it `environment_electrodes`. As always, I am open to naming suggestions, but whatever it is should be clear that these are not electrodes on the surface of the head so 'external_electrodes' would not work. My preference would be for this table to be entirely optional and for it to not have any required fields.

**Comment by oruebel** [comment]
I don't think the spec for ElectricalSeries would need to change for this because all the spec says right now is:

```
- neurodata_type_inc: DynamicTableRegion
    name: electrodes
    doc: the electrodes that this series was generated from
```

So strictly speaking, the spec currently does not say which table of electrodes this has to point to. However, this may (or may not) require changes in the APIs. I'm not sure how tightly they couple ElectricalSeries to the electrodes table. 

With regard to the additional table, if we really need multiple different tables for this (and I'm not sure yet we do), then I think you want to have at least some form of minimal common spec for this.

**Comment by bendichter** [comment]
Yes that's right, it would require no change to `ElectricalSeries` for `ElectricalSeries.electrodes` to reference a region of another table.

We could use a metaclass structure to indicate that these are electrode tables, but that would probably be a breaking change. I cannot think of any columns that should be shared.

Are you really happy with electrodes in the environment being in the `/general/extracellular_ephys/electrodes` table? If not, is there an alternative other than adding a new table?

**Comment by oruebel** [comment]
@bendichter I'd suggest the following solution. If you can implement the first half of #19 ,i .e.,  "Add a new group with ``neurodata_type_def: LabMetadata`` and ``quantity: zero_or_many`` to ``/general``. This would allow labs to add custom metadata by extending ``LabMetadata`` rather than having to modify /general directly". In this way you could add a DynamicTable with the metadata for your electrodes there and in turn reference it via a DynamicTableRegion from ElectricalSeries. This should be a non-breaking schema change.

**Comment by bendichter** [comment]
In the end the simplest solution seems best: For non-neural voltage signals use type `TimeSeries`, set units to `'V'`, and use the `name` and `description` fields to indicate what it is. `ElectricalSeries` is reserved for neural voltage traces.
