### ISSUE TITLE
rate is not a property of starting_time

### ISSUE THREAD

**Issue by tbenst** [NeurodataWithoutBorders/nwb-schema#430]
When I pass `rate` to `TwoPhotonSeries`, it gets stored as an attribute of `acquisition/2p_name/starting_time`. The rate has nothing to do with the starting_time. 

**Describe the solution you'd like / Describe alternatives you've considered**
Perhaps `starting_time` should be renamed to timing, or perhaps `rate` should be a property of `acquisition/2p_name/data` instead?

**Additional context**
code example: https://gist.github.com/tbenst/47bc10936de5cab859bf77bef01194d7

## Checklist

- [x] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues)?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [x] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?

**Comment by rly** [comment]
This is more of a schema issue than a PyNWB issue so I transferred it.

**Comment by rly** [comment]
I agree that semantically, `rate` is not a property of `starting_time`. I think the intention was to tie the two properties together so that one is not present without the other. Unfortunately, because `TimeSeries` is a base type of NWB used by many other types, changing the name or structure of the `starting_time` dataset would be a significant compatibility breaking change. We could change this in a future major version (e.g., 3.0) of NWB though, so I will add this issue to our list of breaking changes to consider.

As a solution, I think it would be better to have separate datasets for `starting_time` and `rate` and expand the schema language to allow specifying that, if `rate` is present, `starting_time` must also be present (and those are mutually exclusive with the `timestamps` dataset). Alternatively, but less elegantly, the datasets `starting_time` and `rate` could be in a new group called `regular_timestamps` or something and have both datasets required within it.

**Comment by rly** [comment]
Closing this issue for now, but we will consider the change in future major versions of NWB. Thanks @tbenst !
