### ISSUE TITLE
[Documentation]: TimeSeries and units field

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwb-schema#514]
Hey, I noticed that the readthedocs view of TimeSeries has `unit` specified three separate times - is this intended?

![image](https://user-images.githubusercontent.com/51133164/164542119-191e3247-b1ab-4c0d-8537-b820ff0481c8.png)
![image](https://user-images.githubusercontent.com/51133164/164542131-d993e726-cc74-4909-8d4e-60c8ec5315db.png)

**Comment by bendichter** [comment]
I think this is unit for data, timestamps, and starting_time, but what appears that the problem is they aren't marked as such

**Comment by rly** [comment]
Ben is correct. I think the dots before "unit" are supposed to depict the hierarchy, but it is definitely not clear. I created an issue in the docutils https://github.com/hdmf-dev/hdmf-docutils/issues/75

**Comment by oruebel** [comment]
> think this is unit for data, timestamps, and starting_time,

Correct. Currently, this is indicated in the table by the number of "." as part of the prefix. The notation used in the tables is described here https://nwb-schema.readthedocs.io/en/latest/format_description.html#notation I.e., the notation in the table looks correct, but there may be better ways to do this.

**Comment by oruebel** [comment]
If I remember correctly, we did this formatting originally because it was consistent with how NWB 1 described the format and because full paths makes the layout very dense. As such, the desire was to have some way to indicate indentation below the previous item in the table. 

BTW, the symbol used to indicate the indentation level is specified here:

https://github.com/NeurodataWithoutBorders/nwb-schema/blob/4cc938f7dd69b6b92c209b084e15aa0c40656b20/docs/format/source/conf_doc_autogen.py#L72-L73

**Comment by CodyCBakerPhD** [comment]
I believe this was resolved with #516, but I'll reopen if I notice it again.
