### ISSUE TITLE
RTD build for storage docs is failing 

### ISSUE THREAD

**Issue by oruebel** [NeurodataWithoutBorders/nwb-schema#585]
The builds for the nwb storage docs are failing due to missing `..readthedocs.yaml` configuration file

See https://readthedocs.org/projects/nwb-storage/builds/

<img width="833" alt="Screen Shot 2024-07-30 at 8 46 11 PM" src="https://github.com/user-attachments/assets/6e9d61e9-7728-47f6-b5e5-e4f649ae3246">

**Comment by stephprince** [comment]
There is a related [issue](https://github.com/NeurodataWithoutBorders/nwb-schema/issues/551) about adding `.readthedocs.yaml` files to NWB / HDMF related projects. I checked the other repos and I think `nwb-storage` is the last one missing the configuration file, so that issue can also be closed with this one.

**Comment by stephprince** [comment]
The build is still failing for a different reason now
